project:
  type: website
  output-dir: _site
  render:
    - ece_one_pager.qmd

website:
  title: "New York City Council"
  search: false

  navbar:
    title: false
    pinned: true
    background: light

    left:
      - text: "FIND MY DISTRICT"
        href: https://council.nyc.gov/districts/
      - text: "BUDGET"
        href: https://council.nyc.gov/budget/
      - text: "COMMITTEES"
        href: https://council.nyc.gov/committees/
      - text: "LAND USE"
        href: https://council.nyc.gov/land-use/
      - text: "LEGISLATION"
        href: https://legistar.council.nyc.gov/Legislation.aspx
      - text: "PRESS RELEASES"
        href: https://council.nyc.gov/press/
      - text: "DATA"
        href: https://council.nyc.gov/data/

    tools:
      - icon: twitter-x
        href: https://x.com/NYCCouncilData
      - icon: github
        href: https://github.com/NewYorkCityCouncil/

format:
  closeread-html:
    cr-style:
      narrative-background-color-overlay: black
      narrative-text-color-overlay: "#e2e2e2"
    theme: cosmo
    css: styles.css
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 2
    toc-title: "In this report"
    smooth-scroll: true
    anchor-sections: true
    include-in-header:
      - progress.html

execute:
  echo: false
  warning: false
  message: false
  freeze: auto
